FROM node:20-alpine AS builder
WORKDIR /app
COPY ./mp-pj/package*.json ./
RUN npm install
COPY ./mp-pj ./
RUN npm run build

FROM nginx:alpine
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html